USE DATABASE MFG_LAKEHOUSE;
USE SCHEMA ANALYTICS;

-- KPI: Defect Rate with 7-day rolling average
CREATE OR REPLACE VIEW KPI_DEFECT_RATE AS
WITH BaseMetrics AS (
    SELECT 
        q.PRODUCTION_LINE,
        q.SHIFT_ID,
        p.PRODUCT_CATEGORY,
        DATE_TRUNC('week', q.PRODUCTION_DATE) AS PROD_WEEK,
        q.PRODUCTION_DATE,
        SUM(q.DEFECT_COUNT) AS TOTAL_DEFECTS,
        SUM(q.TOTAL_INSPECTED) AS TOTAL_UNITS,
        CASE 
            WHEN SUM(q.TOTAL_INSPECTED) = 0 THEN 0 
            ELSE (SUM(q.DEFECT_COUNT) / SUM(q.TOTAL_INSPECTED)) * 100 
        END AS DAILY_DEFECT_RATE
    FROM STAGING.FACT_QUALITY_METRICS q
    LEFT JOIN STAGING.FACT_PRODUCTION fp ON q.BATCH_ID = fp.BATCH_ID
    LEFT JOIN STAGING.DIM_PRODUCT p ON fp.PRODUCT_ID = p.PRODUCT_ID
    GROUP BY 1, 2, 3, 4, 5
)
SELECT 
    PRODUCTION_LINE,
    SHIFT_ID,
    PRODUCT_CATEGORY,
    PROD_WEEK,
    PRODUCTION_DATE,
    TOTAL_DEFECTS,
    TOTAL_UNITS,
    DAILY_DEFECT_RATE,
    -- 7-Day Rolling Average Window Function
    AVG(DAILY_DEFECT_RATE) OVER (
        PARTITION BY PRODUCTION_LINE, SHIFT_ID, PRODUCT_CATEGORY 
        ORDER BY PRODUCTION_DATE 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS ROLLING_7D_DEFECT_RATE
FROM BaseMetrics
ORDER BY PRODUCTION_DATE DESC;
