USE DATABASE MFG_LAKEHOUSE;
USE SCHEMA ANALYTICS;

-- KPI: Throughput Analysis
CREATE OR REPLACE VIEW KPI_THROUGHPUT AS
WITH HourlyThroughput AS (
    SELECT 
        PRODUCTION_LINE,
        SHIFT_ID,
        PRODUCTION_DATE,
        SUM(UNITS_PRODUCED) AS TOTAL_UNITS,
        -- Calculate total duration in hours (assuming start and end time are available)
        SUM(TIMESTAMPDIFF('minute', START_TIME, END_TIME)) / 60.0 AS PROD_HOURS
    FROM STAGING.FACT_PRODUCTION
    GROUP BY 1, 2, 3
),
ThroughputCalculated AS (
    SELECT
        PRODUCTION_LINE,
        SHIFT_ID,
        PRODUCTION_DATE,
        TOTAL_UNITS,
        PROD_HOURS,
        CASE WHEN PROD_HOURS > 0 THEN TOTAL_UNITS / PROD_HOURS ELSE 0 END AS UNITS_PER_HOUR
    FROM HourlyThroughput
)
SELECT
    PRODUCTION_LINE,
    SHIFT_ID,
    PRODUCTION_DATE,
    UNITS_PER_HOUR,
    LAG(UNITS_PER_HOUR) OVER (PARTITION BY PRODUCTION_LINE ORDER BY PRODUCTION_DATE, SHIFT_ID) AS PREV_SHIFT_UPH,
    -- Percent change vs previous shift
    CASE 
        WHEN LAG(UNITS_PER_HOUR) OVER (PARTITION BY PRODUCTION_LINE ORDER BY PRODUCTION_DATE, SHIFT_ID) = 0 THEN NULL
        ELSE (UNITS_PER_HOUR - LAG(UNITS_PER_HOUR) OVER (PARTITION BY PRODUCTION_LINE ORDER BY PRODUCTION_DATE, SHIFT_ID)) / 
             LAG(UNITS_PER_HOUR) OVER (PARTITION BY PRODUCTION_LINE ORDER BY PRODUCTION_DATE, SHIFT_ID) * 100 
    END AS PCT_CHANGE_VS_PREV,
    RANK() OVER (PARTITION BY PRODUCTION_DATE ORDER BY UNITS_PER_HOUR DESC) AS THROUGHPUT_RANK
FROM ThroughputCalculated;
