USE DATABASE MFG_LAKEHOUSE;
USE SCHEMA ANALYTICS;

-- KPI: Material Batch Quality Trends
CREATE OR REPLACE VIEW KPI_MATERIAL_BATCH_TRENDS AS
WITH BatchMetrics AS (
    SELECT
        mb.BATCH_ID,
        mb.MATERIAL_ID,
        mb.SUPPLIER_ID,
        mb.RECEIVED_DATE,
        q.DEFECT_RATE
    FROM STAGING.MATERIAL_BATCHES mb
    -- Assuming a fact table linking material to quality metrics
    JOIN STAGING.FACT_QUALITY_METRICS q ON mb.BATCH_ID = q.BATCH_ID
)
SELECT 
    BATCH_ID,
    MATERIAL_ID,
    SUPPLIER_ID,
    RECEIVED_DATE,
    DEFECT_RATE,
    -- Flag problematic batches
    CASE WHEN DEFECT_RATE > 5.0 THEN TRUE ELSE FALSE END AS IS_HIGH_DEFECT_BATCH,
    -- Lag over last 4 batches from same supplier
    AVG(DEFECT_RATE) OVER (
        PARTITION BY SUPPLIER_ID 
        ORDER BY RECEIVED_DATE
        ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
    ) AS HISTORICAL_AVG_DEFECT_RATE_LAST_4
FROM BatchMetrics
ORDER BY SUPPLIER_ID, RECEIVED_DATE DESC;
