-- Manufacturing Quality and Operations Lakehouse Setup Script

-- 1. Create Database & Schemas
CREATE DATABASE IF NOT EXISTS MFG_LAKEHOUSE;
USE DATABASE MFG_LAKEHOUSE;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- 2. Create Dimensional Tables
CREATE OR REPLACE TABLE STAGING.DIM_MACHINE (
    MACHINE_ID VARCHAR(50) PRIMARY KEY,
    PRODUCTION_LINE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(100),
    INSTALLATION_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
) COMMENT = 'Dimension table for manufacturing machines';

CREATE OR REPLACE TABLE STAGING.DIM_PRODUCT (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_CATEGORY VARCHAR(100),
    UNIT_PRICE DECIMAL(10,2)
);

CREATE OR REPLACE TABLE STAGING.DIM_SHIFT (
    SHIFT_ID VARCHAR(10) PRIMARY KEY,
    SHIFT_NAME VARCHAR(50),
    START_TIME TIME,
    END_TIME TIME
);

-- 3. Create Fact Tables (Staging for Silver Layer)
CREATE OR REPLACE TABLE STAGING.FACT_PRODUCTION (
    BATCH_ID VARCHAR(100) PRIMARY KEY,
    PRODUCT_ID VARCHAR(50),
    PRODUCTION_LINE VARCHAR(50),
    SHIFT_ID VARCHAR(10),
    UNITS_PRODUCED INT NOT NULL,
    PRODUCTION_DATE DATE,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.FACT_INSPECTION (
    INSPECTION_ID VARCHAR(100) PRIMARY KEY,
    BATCH_ID VARCHAR(100),
    DEFECT_FOUND BOOLEAN,
    DEFECT_TYPE VARCHAR(100),
    MEASUREMENT_VALUE DECIMAL(10,4),
    INSPECTOR_ID VARCHAR(50),
    INSPECTION_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.FACT_QUALITY_METRICS (
    PRODUCTION_LINE VARCHAR(50),
    SHIFT_ID VARCHAR(10),
    BATCH_ID VARCHAR(100),
    PRODUCTION_DATE DATE,
    DEFECT_COUNT INT,
    TOTAL_INSPECTED INT,
    DEFECT_RATE DECIMAL(5,2),
    INGESTION_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.FACT_DOWNTIME_METRICS (
    MACHINE_ID VARCHAR(50),
    PRODUCTION_LINE VARCHAR(50),
    SHIFT_ID VARCHAR(10),
    PLANNED_MAINT_MINS INT,
    UNPLANNED_BREAKDOWN_MINS INT,
    CHANGEOVER_MINS INT,
    IDLE_MINS INT,
    TOTAL_DOWNTIME_MINS INT,
    MACHINE_AVAILABILITY_PCT DECIMAL(5,2)
);
